export { HeaderComponent } from "./Header/Header";
export { SortingsComponent } from "./Sortings/Sortings";
export { ColorsFilterComponent } from "./ColorsFilter/ColorsFilter";
export { ProductsComponent } from "./Products/Products";
export { ProductComponent } from "./Product/Product";
export { GoBackButtonComponent } from "./GoBackButton/GoBackButton";
export { DetailProductComponent } from "./DetailProduct/DetailProduct";
export { CartProductComponent } from "./CartProduct/CartProduct";
export { PaginationComponent } from "./Pagination/Pagination";
